# .bashrc

# Fix for sourcing rvmrc
cd .

# Source some stuff
if [ -f /etc/bashrc ]; then
  source /etc/bashrc
fi

PATH=$HOME/bin:$HOME/.rcfiles/bin:$PATH

for f in $HOME/.bash/aliases/*; do source $f; done
for f in $HOME/.bash/completions/*; do source $f; done

complete -cf sudo

export EDITOR="vim"
